-- begin REGISTRATIONOFPASSES_EMPLOYEE
alter table REGISTRATIONOFPASSES_EMPLOYEE add constraint FK_REGISTRATIONOFPASSES_EMPLOYEE_ON_PLACEWORK foreign key (PLACEWORK) references REGISTRATIONOFPASSES_PLACE_WORK(ID)^
create index IDX_REGISTRATIONOFPASSES_EMPLOYEE_ON_PLACEWORK on REGISTRATIONOFPASSES_EMPLOYEE (PLACEWORK)^
-- end REGISTRATIONOFPASSES_EMPLOYEE
-- begin REGISTRATIONOFPASSES_PHONE
alter table REGISTRATIONOFPASSES_PHONE add constraint FK_REGISTRATIONOFPASSES_PHONE_ON_EMPLOYEE foreign key (EMPLOYEE) references REGISTRATIONOFPASSES_EMPLOYEE(ID)^
create index IDX_REGISTRATIONOFPASSES_PHONE_ON_EMPLOYEE on REGISTRATIONOFPASSES_PHONE (EMPLOYEE)^
-- end REGISTRATIONOFPASSES_PHONE
