-- begin REGISTRATIONOFPASSES_EMPLOYEE
alter table REGISTRATIONOFPASSES_EMPLOYEE add constraint FK_REGISTRATIONOFPASSES_EMPLOYEE_ON_PLACEWORK foreign key (PLACEWORK) references REGISTRATIONOFPASSES_PLACE_WORK(ID)^
create index IDX_REGISTRATIONOFPASSES_EMPLOYEE_ON_PLACEWORK on REGISTRATIONOFPASSES_EMPLOYEE (PLACEWORK)^
-- end REGISTRATIONOFPASSES_EMPLOYEE
-- begin REGISTRATIONOFPASSES_PHONE
alter table REGISTRATIONOFPASSES_PHONE add constraint FK_REGISTRATIONOFPASSES_PHONE_ON_EMPLOYEE foreign key (EMPLOYEE) references REGISTRATIONOFPASSES_EMPLOYEE(ID)^
create index IDX_REGISTRATIONOFPASSES_PHONE_ON_EMPLOYEE on REGISTRATIONOFPASSES_PHONE (EMPLOYEE)^
-- end REGISTRATIONOFPASSES_PHONE
-- begin REGISTRATIONOFPASSES_REQUEST
alter table REGISTRATIONOFPASSES_REQUEST add constraint FK_REGISTRATIONOFPASSES_REQUEST_ON_EMPLOYEE foreign key (EMPLOYEE) references REGISTRATIONOFPASSES_EMPLOYEE(ID)^
create index IDX_REGISTRATIONOFPASSES_REQUEST_ON_EMPLOYEE on REGISTRATIONOFPASSES_REQUEST (EMPLOYEE)^
-- end REGISTRATIONOFPASSES_REQUEST
-- begin REQUEST_AREA_LINK
alter table REQUEST_AREA_LINK add constraint FK_REQARE_ON_REQUEST foreign key (REQUEST_ID) references REGISTRATIONOFPASSES_REQUEST(ID)^
alter table REQUEST_AREA_LINK add constraint FK_REQARE_ON_AREA foreign key (AREA_ID) references REGISTRATIONOFPASSES_AREA(ID)^
-- end REQUEST_AREA_LINK
